# Generated by Django 2.2.2 on 2019-07-30 21:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('-pk',), 'verbose_name': 'Version', 'verbose_name_plural': 'Versions'},
        ),
        migrations.RemoveField(
            model_name='version',
            name='format',
        ),
        migrations.RemoveField(
            model_name='version',
            name='serialized_data',
        ),
        migrations.AddField(
            model_name='version',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='The serialized form of this version of the model.', verbose_name='data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='type',
            field=models.CharField(choices=[('initial', 'initial'), ('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('revert', 'revert')], default='initial', max_length=7, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='version',
            name='content_type',
            field=models.ForeignKey(help_text='Content type of the model under version control.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='version',
            name='db',
            field=models.CharField(help_text='The database the model under version control is stored in.', max_length=191, verbose_name='database'),
        ),
        migrations.AlterField(
            model_name='version',
            name='object_id',
            field=models.CharField(help_text='Primary key of the model under version control.', max_length=191, verbose_name='object id'),
        ),
        migrations.AlterField(
            model_name='version',
            name='revision',
            field=models.ForeignKey(help_text='The revision that contains this version.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reversion.Revision', verbose_name='reversion'),
        ),
    ]
